### ISSUE TITLE
Testing new features

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/morphology-pre-annotation-tool#15]
I first updated the tool and deleted the dictionary, then I tryed to run the tool with the no_output switch to first create a new dictionary from the annotated files in my to_dict folder. 

Readme says to use
```
$ cdli-mpa-tool --no_output ./resources   
```
The correct syntax seems to be 
```
$ cdli-mpa-tool -i ./resources -n
```
or
```
cdli-mpa-tool -i ./resources -no_output

```

Output :
```
epp@waga-masta:/alty/data/morphology-pre-annotation-tool$ cdli-mpa-tool -i /alty/data/morphology-pre-annotation-tool/to_dict -n
Annotating the files  [###---------------------------------]   10%First time usage : creating annotation json dictionary file as /home/epp/.cdlimpatool/annotated_morph_dict_v2.json.

Traceback (most recent call last):
  File "/usr/local/bin/cdli-mpa-tool", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cdli_mpa_tool/cli.py", line 32, in main
    check_and_process(pathname, verbose, no_output)
  File "/usr/local/lib/python3.5/dist-packages/cdli_mpa_tool/cli.py", line 17, in check_and_process
    file_process(pathname, verbose, no_output)
  File "/usr/local/lib/python3.5/dist-packages/cdli_mpa_tool/annotate.py", line 77, in file_process
    with codecs.open(outfile_name, 'w+', 'utf-8') as f1:
  File "/usr/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/alty/data/morphology-pre-annotation-tool/to_dict/output/P102310.conll'
```

The tool is looking for the output file which is not created because of the --no_output switch and it generates a fatal error

**Comment by jayanthkmr** [comment]
@epageperron Fixed with this:

https://github.com/cdli-gh/morphology-pre-annotation-tool/commit/98dc8898e0a8f1486fffcd786eb5ea7898465eb4

**Comment by epageperron** [comment]
Now works like a charm!
