### ISSUE TITLE
facing this error today after clean install and trying to ingest dictionary

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/morphology-pre-annotation-tool#29]
epp-mtaac:Desktop emilie$ mpat -n -i ./to_dict
Processing the files  [#######-----------------------------]   19%  0d 00:00:23
Traceback (most recent call last):
  File "/usr/local/bin/mpat", line 11, in <module>
    load_entry_point('cdlimpatool==0.5.7', 'console_scripts', 'mpat')()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cdli_mpa_tool/cli.py", line 53, in main
    check_and_process(pathname, no_output, check, format_conll, verbose)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cdli_mpa_tool/cli.py", line 25, in check_and_process
    annotator.process()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cdli_mpa_tool/annotate.py", line 118, in process
    self.__file_process()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cdli_mpa_tool/annotate.py", line 106, in __file_process
    self.__line_process(line)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cdli_mpa_tool/annotate.py", line 62, in __line_process
    if line[0] != '#':
IndexError: string index out of range
epp-mtaac:Desktop emilie$

**Comment by epageperron** [comment]
@jayanthjaiswal

**Comment by jayanthkmr** [comment]
@epageperron Resolved here - https://github.com/cdli-gh/morphology-pre-annotation-tool/commit/98923fda721741e97dc95bc2fb850eddf35878f2 Also, use the latest version of mpat tool - 0.6.0.
