### ISSUE TITLE
Results of Initial Test

### ISSUE THREAD

**Issue by enkiduderino** [cdli-gh/morphology-pre-annotation-tool#7]
Here are the results from my initial tests of the pre-annotation tool:

Installation was smooth.

1. I ran the tool on a folder of 5 already annotated texts in .conll format. The dictionary generated and looks like it should. The tool also created .tsv versions of the files, which were identical to the .conll.

2. Next I ran the tool on a folder of blank versions of 4 of the same texts. This time I encountered an error: TypeError: writelines() argument must be a sequence of strings

  [inside-65-107-17:mpa pnao$ sudo cdli-mpa-tool -i ./resources/blank
  Annotating the files  [#########---------------------------]   25%
  Traceback (most recent call last):
    File "/usr/local/bin/cdli-mpa-tool", line 9, in <module>
      load_entry_point('cdlimpatool==0.1.2', 'console_scripts', 'cdli-mpa-tool')()
    File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
      return self.main(*args, **kwargs)
    File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
      rv = self.invoke(ctx)
    File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
      return callback(*args, **kwargs)
    File "/Library/Python/2.7/site-packages/cdli_mpa_tool/cli.py", line 82, in main
      check_and_process(pathname, verbose)
    File "/Library/Python/2.7/site-packages/cdli_mpa_tool/cli.py", line 70, in check_and_process
      file_process(pathname, verbose)
    File "/Library/Python/2.7/site-packages/cdli_mpa_tool/cli.py", line 60, in file_process
      f1.writelines(line)
  TypeError: writelines() argument must be a sequence of string

This error repeated as I ran the tool on each blank .conll individually.

Despite the error, the tool did generate a partial .tsv version of the file in each case that terminates at the point of the error. The lines before the error was encountered all appear to be properly annotated in the manner of the original files that were used to train the tool.

All of the .conll files I used and the resulting .tsv files can be found here
https://drive.google.com/open?id=1CKdQzm7Y5bifJWf0hoxJMU_Zqi07NC3V

**Comment by jayanthkmr** [comment]
Thanks. I will continue working on it after my end quarters.

**Comment by jayanthkmr** [comment]
@enkiduderino  Fixed with https://github.com/cdli-gh/morphology-pre-annotation-tool/pull/9. Please test again and close this issue.
